### ISSUE TITLE
Trying to delete file gives error

### ISSUE THREAD

**Issue by izaddoost** [opendocman/opendocman#250]
Hi dear,
trying to delete file in Admin panel>admin>file>Rejections in version 1.3.5 gives this error.

```
Not Found
The requested URL /delete.php?mode=tmpdel&id0=4&id1=5&id2=6&num_checkboxes=3 was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

but  /delete.php exist on server. 
please help.

**Comment by stephenlawrence** [comment]
Make sure your baseUrl site setting is correct.

**Comment by sekerier** [comment]
I just ran into the same problem with my install, and solved it by modifying the "delete.php". My message included the hexadecimal codes instead of the special characters (%3F for ?, %3D for =, %26 for &). That led me to line 116 in the php file, which had two urlencode directives in it. Removing those solved my problem: I can delete those files again.
