### ISSUE TITLE
html entity displayed

### ISSUE THREAD

**Issue by olimaz** [opendocman/opendocman#277]
I'm using the spanish translation , App Version: 1.3.5, Database Version: 1.3.0.

All special characters are being displayed as "iacute;" and so on.

<img width="686" alt="bug" src="https://user-images.githubusercontent.com/8838947/57052495-2d4fd900-6c4d-11e9-80be-51ac9a02c6f6.png">

**Comment by billygl** [comment]
I have the same issue with version 1.3.5.
The problem is due to functions.php in line 726.
````
function msg($s)
{
    if (isset($GLOBALS['lang'][$s])) {
        return e::h($GLOBALS['lang'][$s]);
    } else {
        return $s;
    }
}
````
It is ok when translations doesn't have html entites. But Spanish translation has html entities.
Update /includes/language/spanish.php. Remove html entities to normal form. Eg. &amp;aacut
[spanish.php.txt](https://github.com/opendocman/opendocman/files/3962104/spanish.php.txt)

e; to á.
As the HTML page supports UTF-8, it will look ok.
I attached the spanish.php but with .txt to upload to github
